### ISSUE TITLE
Include complete code on project

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/slug#7]
There have been a few comments that learners are struggling with the SLUG project and have requested the complete code. It would be a good idea to make this available, or provide the code listing at points throughout the project.

slug | URL: /en/projects/slug/5 somehow, the program doesn't work! we are doing everything correct but it tells us that we are not right! Please check it. And it would be nice from you to have the answers on it! | 2019-02-15 13:09:03.173167
-- | -- | --

**Comment by martinohanlon** [comment]
@daraghbroderick you ok to this the up?

**Comment by daraghbroderick** [comment]
Sure, I'll take a look at this tomorrow.

**Comment by daraghbroderick** [comment]
Linked to complete code at the start under additional information for educators. This project is a nice one for those a little more advanced and including more code throughout might spoil this.
